# Build stage
FROM public.ecr.aws/docker/library/node:24-slim AS builder
WORKDIR /app

ARG WEBINY_API_URL
ARG WEBINY_API_TOKEN
ARG COGNITO_USER_POOL_ID
ARG COGNITO_CLIENT_ID
ARG COGNITO_REGION=ap-southeast-2
ARG FAN_PREFERENCES_TABLE
ARG FAN_DELETION_AUDIT_TABLE
ARG KMS_KEY_ARN
ARG COOKIE_DOMAIN
ARG COOKIE_SECURE=true
ARG NEXT_PUBLIC_APP_URL

ENV WEBINY_API_URL=$WEBINY_API_URL
ENV WEBINY_API_TOKEN=$WEBINY_API_TOKEN
ENV COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
ENV COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
ENV COGNITO_REGION=$COGNITO_REGION
ENV FAN_PREFERENCES_TABLE=$FAN_PREFERENCES_TABLE
ENV FAN_DELETION_AUDIT_TABLE=$FAN_DELETION_AUDIT_TABLE
ENV KMS_KEY_ARN=$KMS_KEY_ARN
ENV COOKIE_DOMAIN=$COOKIE_DOMAIN
ENV COOKIE_SECURE=$COOKIE_SECURE
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Production stage
FROM public.ecr.aws/docker/library/node:24-slim AS runner

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.0.1 /lambda-adapter /opt/extensions/lambda-adapter

ARG WEBINY_API_URL
ARG WEBINY_API_TOKEN
ARG COGNITO_USER_POOL_ID
ARG COGNITO_CLIENT_ID
ARG COGNITO_REGION=ap-southeast-2
ARG FAN_PREFERENCES_TABLE
ARG FAN_DELETION_AUDIT_TABLE
ARG KMS_KEY_ARN
ARG COOKIE_DOMAIN
ARG COOKIE_SECURE=true
ARG NEXT_PUBLIC_APP_URL

ENV PORT=3000
ENV NODE_ENV=production
ENV WEBINY_API_URL=${WEBINY_API_URL}
ENV WEBINY_API_TOKEN=${WEBINY_API_TOKEN}
ENV COGNITO_USER_POOL_ID=${COGNITO_USER_POOL_ID}
ENV COGNITO_CLIENT_ID=${COGNITO_CLIENT_ID}
ENV COGNITO_REGION=${COGNITO_REGION}
ENV FAN_PREFERENCES_TABLE=${FAN_PREFERENCES_TABLE}
ENV FAN_DELETION_AUDIT_TABLE=${FAN_DELETION_AUDIT_TABLE}
ENV KMS_KEY_ARN=${KMS_KEY_ARN}
ENV COOKIE_DOMAIN=${COOKIE_DOMAIN}
ENV COOKIE_SECURE=${COOKIE_SECURE}
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}

WORKDIR /app

COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/run.sh ./run.sh
RUN ln -s /tmp/cache ./.next/cache

CMD ["./run.sh"]
